// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.normandy.startupRolloutPrefs.services.sync.engine.bookmarks.buffer", true);
user_pref("app.normandy.user_id", "a6715488-0118-4020-ac28-a19264e8f49c");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1577116975);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1577117095);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1577116495);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1577116735);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1577116615);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1577116855);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1577116525);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1577117215);
user_pref("browser.bookmarks.editDialog.confirmationHintShowCount", 2);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 10293);
user_pref("browser.cache.disk.capacity", 788480);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1577116465);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 87);
user_pref("browser.newtabpage.activity-stream.impressionId", "{73eefef1-8d19-42b5-a0ef-22968cb40782}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1577118395660");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1577120184660");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1577116487550");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1577120087550");
user_pref("browser.search.region", "EG");
user_pref("browser.slowStartup.averageTime", 6599);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20191205184924");
user_pref("browser.startup.homepage_override.mstone", "71.0");
user_pref("browser.startup.lastColdStartupCheck", 1577116469);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1577116478780");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "71.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "07296f8b8b844516b96a33e5b5703d7f");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Fri, 20 Dec 2019 22:42:36 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1577116976);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "71.0");
user_pref("extensions.lastPlatformVersion", "71.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"7feb3f8b-a745-4428-9eec-48862290633b\",\"screenshots@mozilla.org\":\"39095e34-cb08-48aa-866b-f34f6188e877\",\"webcompat-reporter@mozilla.org\":\"3b97e38c-2718-4988-85c8-75841943cdc2\",\"webcompat@mozilla.org\":\"5b2b8c8f-e253-4567-9717-06b123c96680\",\"default-theme@mozilla.org\":\"9ee75269-a1eb-46dd-a05b-423ac5f9aea6\",\"google@search.mozilla.org\":\"255fbc04-2bad-4f53-8fb9-6e8014d0c1df\",\"amazondotcom@search.mozilla.org\":\"9e11993a-5d51-4d85-a607-4106f1c1dd51\",\"bing@search.mozilla.org\":\"469c580a-6d0f-430e-b3d3-9c753d29a941\",\"ddg@search.mozilla.org\":\"361dc5e4-b65f-49f0-8b2f-1def5f0be027\",\"ebay@search.mozilla.org\":\"43f4d2d9-9fa6-4c21-bf5c-f0a315e5c181\",\"twitter@search.mozilla.org\":\"a45a108e-cb8c-4c46-baf4-9eb5aa6ed241\",\"wikipedia@search.mozilla.org\":\"c1864487-ce3f-4f71-8b4c-c34b492be412\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1577118621);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1577116606);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20191205184924");
user_pref("media.gmp-manager.lastCheck", 1577116603);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1577118621);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "a289ac88-767c-45bf-8bd8-a59e57fd1b2a");
user_pref("security.sandbox.plugin.tempDirSuffix", "7e09bfbd-ccb2-41ad-af97-addc399f1c0d");
user_pref("services.blocklist.pinning.checked", 1577116605);
user_pref("services.settings.clock_skew_seconds", -80);
user_pref("services.settings.last_etag", "\"1576886481064\"");
user_pref("services.settings.last_update_seconds", 1577116935);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1577116605);
user_pref("services.settings.main.cfr-fxa.last_check", 1577116605);
user_pref("services.settings.main.cfr.last_check", 1577116605);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1577116605);
user_pref("services.settings.main.hijack-blocklists.last_check", 1577116605);
user_pref("services.settings.main.language-dictionaries.last_check", 1577116605);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1577116605);
user_pref("services.settings.main.public-suffix-list.last_check", 1577116605);
user_pref("services.settings.main.sites-classification.last_check", 1577116605);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1577116605);
user_pref("services.settings.main.whats-new-panel.last_check", 1577116605);
user_pref("services.settings.security.onecrl.checked", 1577116605);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1577118621);
user_pref("toolkit.startup.last_success", 1577116462);
user_pref("toolkit.telemetry.cachedClientID", "c68fc73a-0126-4129-842d-ce6b8d229981");
user_pref("toolkit.telemetry.previousBuildID", "20191205184924");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "control");
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("trailhead.firstrun.interruptsExperiment", "modal_variant_f");
